ALTER TABLE "app_settings" ADD COLUMN IF NOT EXISTS "ollamaCpuLimit" INTEGER NOT NULL DEFAULT 80;
ALTER TABLE "app_settings" ADD COLUMN IF NOT EXISTS "ollamaRamLimit" INTEGER NOT NULL DEFAULT 4;
ALTER TABLE "app_settings" ADD COLUMN IF NOT EXISTS "whisperCpuLimit" INTEGER NOT NULL DEFAULT 80;
ALTER TABLE "app_settings" ADD COLUMN IF NOT EXISTS "whisperRamLimit" INTEGER NOT NULL DEFAULT 4;